In [ ]:
# Question 1: Warm-up: Rebuild the basics

import numpy as np  
array_1d = np.arange(10, 20)
print(array_1d, '\n')
print('array_1d Shape:' , array_1d.shape , '\n')
print('array_1d NDimensions:' , array_1d.ndim , '\n')
print('array_1d Data Type:' , array_1d.dtype , '\n')

array_2d = np.full ([4,3], 1.5)
print(array_2d, '\n')
print('array_2d Shape:' , array_2d.shape , '\n')
print('array_2d NDimensions:' , array_2d.ndim , '\n')
print('array_2d Data Type:' , array_2d.dtype , '\n')

array_3d = np.zeros ([2,2,3])
print('array_3d Shape:' , array_3d.shape , '\n')
print('array_3d NDimensions:' , array_3d.ndim , '\n')
print('array_3d Data Type:' , array_3d.dtype , '\n')

array_2d = array_2d.astype('int')
print('array_2d Data Type:' , array_2d.dtype , '\n')

# I would use float data type instead of int when it contains decimal values such as prices and precise calculations. int only covers whole numbers and would not be suitable for such cases.


[10 11 12 13 14 15 16 17 18 19] 

array_1d Shape: (10,) 

array_1d NDimensions: 1 

array_1d Data Type: int64 

[[1.5 1.5 1.5]
 [1.5 1.5 1.5]
 [1.5 1.5 1.5]
 [1.5 1.5 1.5]] 

array_2d Shape: (4, 3) 

array_2d NDimensions: 2 

array_2d Data Type: float64 

array_3d Shape: (2, 2, 3) 

array_3d NDimensions: 3 

array_3d Data Type: float64 

array_2d Data Type: int64 



In [ ]:
# Question 2: Sales table drill: Indexing and slicing

import numpy as np

sales = np.array([
    [120, 135, 110, 145, 130],  # Region A
    [ 90,  85,  95, 100, 110],  # Region B
    [200, 215, 190, 225, 245],  # Region C
    [155, 140, 135, 160, 170]   # Region D
])
regions = np.array(["A", "B", "C", "D"])
quarters = np.array(["Q1", "Q2", "Q3", "Q4", "Q5"])

region_b = np.array (sales[1:2, :])
print (region_b, '\n')
print (region_b.shape, '\n')
# 1D shape as it has one row and five columns

sub_array = np.array (sales[:, 1:5])
print (sub_array, '\n')
print (sub_array.shape, '\n')
# 2D shape as it has 4 rows and 4 columns

q5_sales = np.array (sales[:, 4:5])
q5_sales = q5_sales.flatten()
print (q5_sales, '\n')
print (q5_sales.shape, '\n')
# 1D shape as it has 1 rows and 4 columns

[[ 90  85  95 100 110]] 

(1, 5) 

[[135 110 145 130]
 [ 85  95 100 110]
 [215 190 225 245]
 [140 135 160 170]] 

(4, 4) 

(4, 1) 

[130 110 245 170] 

(4,) 



In [ ]:
# Question 3: Boolean masks: Work with targets

import numpy as np

names = np.array(["Ana", "Ben", "Chen", "Dana", "Eli", "Fatima", "George", "Hui"])
spend = np.array([200, 150, 300, 120, 180, 220, 160, 310])      # marketing spend
revenue = np.array([400, 180, 500, 100, 220, 260, 150, 600])   # revenue

roi = revenue / spend
print(roi, '\n')

roi_mask = roi >= 2.0
print('Mask for ROI >= 2.0: ', roi_mask, '\n')

# Apply mask to filter names, spend, and revenue for customers with ROI >= 2.0
print(names[roi_mask], '\n')
print(spend[roi_mask], '\n')
print(revenue[roi_mask], '\n')

roi_mask2 = spend >= 200
print ('Mask for Spend >= 200: ', roi_mask2, '\n')

roi_mask_combined = roi_mask & roi_mask2
print('Mask for Spend >=200 AND ROI >=2.0: ', roi_mask_combined, '\n')

print('Names for Combined ROI Mask: ', names[roi_mask_combined], '\n')

# This filtered group of customers has a high ROI and also a high marketing spend, which may indicate that they are valuable customers worth investing in further.

[2.         1.2        1.66666667 0.83333333 1.22222222 1.18181818
 0.9375     1.93548387] 

Mask for ROI >= 2.0:  [ True False False False False False False False] 

['Ana'] 

[200] 

[400] 

Mask for Spend >= 200:  [ True False  True False False  True False  True] 

Mask for Spend >=200 AND ROI >=2.0:  [ True False False False False False False False] 

Names for Combined ROI Mask:  ['Ana'] 



In [ ]:
# Question 4: Gradebook: Aggregations and broadcasting

import numpy as np
students = np.array(["S1", "S2", "S3", "S4", "S5"])
subjects = np.array(["Math", "Stats", "Python"])

scores = np.array([
    [75, 80, 85],
    [60, 65, 70],
    [90, 88, 92],
    [82, 79, 84],
    [70, 72, 78]
])

for i in range(len(students)):
    student_scores = scores[i]
    average_score = np.mean(student_scores)
    print(f"{students[i]}'s average score: {average_score:.2f}")

for i in range(len(subjects)):
    subject_scores = scores[:, i]
    average_score = np.mean(subject_scores)
    print(f"Average score for {subjects[i]}: {average_score:.2f}")

# 1. Calculate the mean for each subject (axis=0 averages down the columns)
subject_means = scores.mean(axis=0)
print ("Subject Means:", subject_means, '\n')

# 2. Subtract the means from the scores (Broadcasting)
scores_centered = scores - subject_means
print ("Centered Scores:\n", scores_centered, '\n')

raw_average = scores.mean(axis=1)
print ("Raw Averages:", raw_average, '\n')

centered_average = scores_centered.mean(axis=1)
print ("Centered Averages:", centered_average, '\n')

max_raw_average = np.max(raw_average)
print ("Max Raw Average:", max_raw_average, '\n')
student_with_max_raw_average = students[np.argmax(raw_average)]
print(f"Student with Max Raw Average: {student_with_max_raw_average} with a score of {max_raw_average:.2f}\n")

max_centered_average = np.max(centered_average)
print ("Max Centered Average:", max_centered_average, '\n')
student_with_max_centered_average = students[np.argmax(centered_average)]
print(f"Student with Max Centered Average: {student_with_max_centered_average} with a score of {max_centered_average:.2f}\n")

# The student with the highest raw average is S3, while the student with the highest centered average is also S3. This indicates that S3 performed well across all subjects, even after accounting for the average performance in each subject.
# Centered averages provide a more balanced view of student performance by normalizing for subject difficulty, while raw averages may be skewed by particularly high or low scores in certain subjects.

S1's average score: 80.00
S2's average score: 65.00
S3's average score: 90.00
S4's average score: 81.67
S5's average score: 73.33
Average score for Math: 75.40
Average score for Stats: 76.80
Average score for Python: 81.80
Subject Means: [75.4 76.8 81.8] 

Centered Scores:
 [[ -0.4   3.2   3.2]
 [-15.4 -11.8 -11.8]
 [ 14.6  11.2  10.2]
 [  6.6   2.2   2.2]
 [ -5.4  -4.8  -3.8]] 

Raw Averages: [80.         65.         90.         81.66666667 73.33333333] 

Centered Averages: [  2.         -13.          12.           3.66666667  -4.66666667] 

Max Raw Average: 90.0 

Student with Max Raw Average: S3 with a score of 90.00

Max Centered Average: 12.0 

Student with Max Centered Average: S3 with a score of 12.00

