In [ ]:
import numpy as np  
array_1d = np.arange(10, 20)
print(array_1d, '\n')
print('array_1d Shape:' , array_1d.shape , '\n')
print('array_1d NDimensions:' , array_1d.ndim , '\n')
print('array_1d Data Type:' , array_1d.dtype , '\n')

array_2d = np.full ([4,3], 1.5)
print(array_2d, '\n')
print('array_2d Shape:' , array_2d.shape , '\n')
print('array_2d NDimensions:' , array_2d.ndim , '\n')
print('array_2d Data Type:' , array_2d.dtype , '\n')

array_3d = np.zeros ([2,2,3])
print('array_3d Shape:' , array_3d.shape , '\n')
print('array_3d NDimensions:' , array_3d.ndim , '\n')
print('array_3d Data Type:' , array_3d.dtype , '\n')

array_2d = array_2d.astype('int')
print('array_2d Data Type:' , array_2d.dtype , '\n')

# I would use float data type instead of int when it contains decimal values such as prices and precise calculations. int only covers whole numbers and would not be suitable for such cases.


[10 11 12 13 14 15 16 17 18 19] 

array_1d Shape: (10,) 

array_1d NDimensions: 1 

array_1d Data Type: int64 

[[1.5 1.5 1.5]
 [1.5 1.5 1.5]
 [1.5 1.5 1.5]
 [1.5 1.5 1.5]] 

array_2d Shape: (4, 3) 

array_2d NDimensions: 2 

array_2d Data Type: float64 

array_3d Shape: (2, 2, 3) 

array_3d NDimensions: 3 

array_3d Data Type: float64 

array_2d Data Type: int64 



In [ ]:
import numpy as np

sales = np.array([
    [120, 135, 110, 145, 130],  # Region A
    [ 90,  85,  95, 100, 110],  # Region B
    [200, 215, 190, 225, 245],  # Region C
    [155, 140, 135, 160, 170]   # Region D
])
regions = np.array(["A", "B", "C", "D"])
quarters = np.array(["Q1", "Q2", "Q3", "Q4", "Q5"])

region_b = np.array (sales[1:2, :])
print (region_b, '\n')
print (region_b.shape, '\n')
# 1D shape as it has one row and five columns

sub_array = np.array (sales[:, 1:5])
print (sub_array, '\n')
print (sub_array.shape, '\n')
# 2D shape as it has 4 rows and 4 columns

q5_sales = np.array (sales[:, 4:5])
q5_sales = q5_sales.flatten()
print (q5_sales, '\n')
print (q5_sales.shape, '\n')
# 1D shape as it has 1 rows and 4 columns

[[ 90  85  95 100 110]] 

(1, 5) 

[[135 110 145 130]
 [ 85  95 100 110]
 [215 190 225 245]
 [140 135 160 170]] 

(4, 4) 

(4, 1) 

[130 110 245 170] 

(4,) 

